with Ada.Streams;
with Flyology_Wire.Codecs;
with Generated_Profile_1_Bytes_Test_Codec;
with Interfaces;
with Profile_1_Bytes_Test_Types;
with System;

procedure Generated_Bytes_Codec_Smoke is
   package Wire renames Flyology_Wire;
   package Codecs renames Flyology_Wire.Codecs;
   package Codec renames Generated_Profile_1_Bytes_Test_Codec;

   use type Ada.Streams.Stream_Element_Array;
   use type Codecs.Decode_Status;
   use type Codecs.Encode_Status;
   use type Codecs.Measure_Status;
   use type Codecs.Size_Bound;
   use type Interfaces.Unsigned_64;
   use type Profile_1_Bytes_Test_Types.Value;
   use type System.Address;
   use type Wire.Byte_Count;
   use type Wire.Octet;
   use type Wire.Octet_Count;

   procedure Assert (Condition : Boolean; Message : String) is
   begin
      if not Condition then
         raise Program_Error with Message;
      end if;
   end Assert;

   Source         : constant Codec.Value :=
     (Code => 5, Data => [16#AA#, 16#BB#, 16#CC#, 0], Data_Length => 3);
   Empty_Source   : constant Codec.Value := (Code => 5, Data => [others => 16#EE#], Data_Length => 0);
   Invalid_Source : constant Codec.Value := (Code => 5, Data => [others => 0], Data_Length => 5);
   Empty_Decoded  : constant Codec.Value := (Code => 5, Data => [others => 0], Data_Length => 0);
   Failure_Value  : constant Codec.Value := (Code => 1, Data => [others => 0], Data_Length => 0);
   Expected       : constant Wire.Octet_Array := [1, 1, 5, 2, 3, 16#AA#, 16#BB#, 16#CC#];
   Empty_Expected : constant Wire.Octet_Array := [1, 1, 5, 2, 0];
   Too_Long       : constant Wire.Octet_Array := [1, 1, 5, 2, 5, 1, 2, 3, 4, 5];
   Missing_Data   : constant Wire.Octet_Array := [1, 1, 5];
   Output         : Wire.Octet_Array (10 .. 21) := [others => 16#A5#];
   Before         : Wire.Octet_Array (10 .. 21);
   Payload        : aliased Wire.Octet_Array (20 .. 27) := [1, 1, 5, 2, 3, 16#AA#, 16#BB#, 16#CC#];
   Decoded        : Codec.Value;
   Size           : Wire.Byte_Count;
   Written        : Wire.Octet_Count;
   Measure_Result : Codecs.Measure_Status;
   Encode_Result  : Codecs.Encode_Status;
   Decode_Result  : Codecs.Decode_Status;

   Calls            : Natural := 0;
   Observed_Code    : Interfaces.Unsigned_64 := 0;
   Observed_Data    : Wire.Octet_Array (1 .. 3) := [others => 0];
   Expected_Address : System.Address := System.Null_Address;
   Same_Address     : Boolean := False;

   procedure Visit_Code (Value : Interfaces.Unsigned_64) is
   begin
      Calls := Calls + 1;
      Observed_Code := Value;
   end Visit_Code;

   procedure Visit_Data (Value : Wire.Octet_Array) is
   begin
      Calls := Calls + 1;
      Observed_Data := Value;
      Same_Address := Value'Address = Expected_Address;
   end Visit_Data;

   procedure Observe is new Codec.Validate_And_Visit (Visit_Code, Visit_Data);

   Visitor_Error : exception;

   procedure Ignore_Code (Value : Interfaces.Unsigned_64) is
      pragma Unreferenced (Value);
   begin
      null;
   end Ignore_Code;

   Empty_Length : Natural := Natural'Last;

   procedure Visit_Empty_Data (Value : Wire.Octet_Array) is
   begin
      Empty_Length := Value'Length;
   end Visit_Empty_Data;

   procedure Empty_Observe is new Codec.Validate_And_Visit (Ignore_Code, Visit_Empty_Data);

   procedure Raise_From_Data (Value : Wire.Octet_Array) is
      pragma Unreferenced (Value);
   begin
      raise Visitor_Error;
   end Raise_From_Data;

   procedure Raising_Observe is new Codec.Validate_And_Visit (Ignore_Code, Raise_From_Data);

   Raised       : Boolean := False;
   Wrong_Writer : Codecs.Schema_Identity := Codec.Local_Schema;
begin
   Codec.Contract.Measure (Source, Size, Measure_Result);
   Assert
     (Measure_Result = Codecs.Measured
      and then Size = 8
      and then Codec.Value_Descriptor.Maximum_Encoded_Size = Codecs.Bounded (10),
      "generated bytes measure or maximum is incorrect");
   Codec.Contract.Measure (Invalid_Source, Size, Measure_Result);
   Assert
     (Measure_Result = Codecs.Invalid_Value and then Size = 0,
      "generated bytes measure accepted a length above capacity");

   Before := Output;
   Codec.Contract.Encode (Invalid_Source, Output, Written, Encode_Result);
   Assert
     (Encode_Result = Codecs.Invalid_Value and then Written = 0 and then Output = Before,
      "invalid generated bytes encode modified its destination");
   Codec.Contract.Encode (Source, Output, Written, Encode_Result);
   Assert
     (Encode_Result = Codecs.Encoded and then Written = 8 and then Output (10 .. 17) = Expected,
      "generated bytes codec emitted wrong canonical bytes");
   Codec.Contract.Encode (Empty_Source, Output, Written, Encode_Result);
   Assert
     (Encode_Result = Codecs.Encoded and then Written = 5 and then Output (10 .. 14) = Empty_Expected,
      "generated bytes codec did not encode an empty required byte value");

   Codec.Contract.Decode (Codec.Local_Schema, Expected, Decoded, Decode_Result);
   Assert
     (Decode_Result = Codecs.Decoded and then Decoded = Source and then Decoded.Data (6) = 0,
      "generated bytes codec did not round trip or normalize unused capacity");
   Codec.Contract.Decode (Codec.Local_Schema, Empty_Expected, Decoded, Decode_Result);
   Assert
     (Decode_Result = Codecs.Decoded and then Decoded = Empty_Decoded,
      "generated bytes codec did not construct an empty byte value");
   Codec.Contract.Decode (Codec.Local_Schema, Too_Long, Decoded, Decode_Result);
   Assert
     (Decode_Result = Codecs.Invalid_Value and then Decoded = Failure_Value,
      "generated bytes decode accepted an over-limit value or partially published");
   Codec.Contract.Decode (Codec.Local_Schema, Missing_Data, Decoded, Decode_Result);
   Assert
     (Decode_Result = Codecs.Invalid_Value and then Decoded = Failure_Value,
      "generated bytes decode accepted a missing required value or partially published");

   Expected_Address := Payload (25)'Address;
   Observe (Codec.Local_Schema, Payload, Decode_Result);
   Assert
     (Decode_Result = Codecs.Decoded
      and then Calls = 2
      and then Observed_Code = 5
      and then Observed_Data = [16#AA#, 16#BB#, 16#CC#]
      and then Same_Address,
      "generated observer did not lend the validated logical value in caller storage");
   Observe (Codec.Local_Schema, Too_Long, Decode_Result);
   Assert
     (Decode_Result = Codecs.Invalid_Value and then Calls = 2,
      "invalid generated bytes payload invoked an application callback");
   Empty_Observe (Codec.Local_Schema, Empty_Expected, Decode_Result);
   Assert
     (Decode_Result = Codecs.Decoded and then Empty_Length = 0,
      "generated observer did not preserve an empty byte value");

   Wrong_Writer.Fingerprint := [0 => 16#EE#, others => 0];
   Observe (Wrong_Writer, Payload, Decode_Result);
   Assert
     (Decode_Result = Codecs.Incompatible and then Calls = 2,
      "generated observer invoked an application callback for an incompatible writer");

   begin
      Raising_Observe (Codec.Local_Schema, Payload, Decode_Result);
   exception
      when Visitor_Error =>
         Raised := True;
   end;
   Assert (Raised, "generated observer converted an application exception into a status");
end Generated_Bytes_Codec_Smoke;
